apiVersion: v1
kind: PersistentVolume
metadata:
  name: github-backup-pv
  namespace: github
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/github-backups"