apiVersion: v1
kind: Service
metadata:
  name: backup-service
  namespace: github
spec:
  type: NodePort
  selector:
    app: github-backup
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30007